[AppInfo]
app_name = AssociazioneWindsurfCeresioApp
app_author = GiorgioBalzarotti ; <--- METTI QUI IL TUO NOME O ORGANIZZAZIONE

[Database]
# database_name = applicazionedb.db
# Se specificato, questo sovrascrive il percorso calcolato
# automaticamente da appdirs o quello per lo sviluppo.
# Lascia vuoto per il comportamento automatico.
database_path =